# Generated by Django 5.2.9 on 2025-12-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='sales',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
