# Generated by Django 5.2.9 on 2025-12-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0002_branch_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='required_staff',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='branch',
            name='total_staff',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
