# Generated by Django 5.2.9 on 2025-12-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0003_branch_required_staff_branch_total_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='Eid',
            field=models.CharField(default=1, editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
