# Generated by Django 5.2.9 on 2025-12-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0004_employees_eid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='is_active',
        ),
        migrations.AddField(
            model_name='branch',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('renovating', 'Renovating'), ('deactivated', 'Deactivated')], default='active', max_length=20),
        ),
    ]
