# Generated by Django 5.2.9 on 2025-12-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0005_remove_branch_is_active_branch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='employees/profile_pics/'),
        ),
    ]
