# Generated by Django 5.2.9 on 2026-01-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0007_remove_customer_address_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
