# Generated by Django 5.2.9 on 2026-01-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0008_alter_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active_token_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
