# Generated by Django 5.2.9 on 2026-01-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0009_customer_active_token_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='active_token_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
