# Generated by Django 5.2.9 on 2026-01-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0011_menuitem_branchmenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
    ]
