# Generated by Django 5.2.9 on 2026-01-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0012_menuitem_is_veg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('starter', 'Staeter'), ('rice', 'Rice'), ('biryani', 'Biryani'), ('currie', 'Currie'), ('tandoori', 'Tandoori'), ('fastfood', 'Fast Food'), ('tiffin', 'Tiffin'), ('dessert', 'Dessert'), ('beverages', 'Beverages')], max_length=50),
        ),
    ]
