# Generated by Django 5.2.9 on 2026-01-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0013_alter_menuitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='gst_percentage',
        ),
    ]
