# Generated by Django 5.2.9 on 2026-01-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0014_remove_menuitem_gst_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
