# Generated by Django 5.2.9 on 2026-01-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0015_alter_employees_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
