# Generated by Django 5.2.9 on 2026-01-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0016_employees_is_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='is_working',
            field=models.BooleanField(default=False),
        ),
    ]
