# Generated by Django 5.2.9 on 2026-01-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0018_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('upto', 'Upto Percentage'), ('flat', 'Flat Amount')], max_length=20),
        ),
    ]
