# Generated by Django 5.2.9 on 2026-01-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0019_remove_offer_created_by_alter_offer_offer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('timeout', 'Timeout')], default='pending', max_length=20),
        ),
    ]
