# Generated by Django 5.2.9 on 2026-01-18 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0020_stockrequest_expires_at_alter_stockrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='gst_percentage',
        ),
    ]
