# Generated by Django 5.2.9 on 2026-01-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0021_remove_item_gst_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_pic',
            field=models.ImageField(blank=True, null=True, upload_to='items/pics/'),
        ),
    ]
