# Generated by Django 5.2.9 on 2026-01-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0022_item_item_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unit',
        ),
    ]
