# Generated by Django 5.2.9 on 2026-01-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0023_remove_item_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='godownstock',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
