# Generated by Django 5.2.9 on 2026-01-18 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0024_godownstock_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='godownstock',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TFF.item', unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
