# Generated by Django 5.2.9 on 2026-01-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0025_alter_godownstock_item_alter_item_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('ltr', 'Litre'), ('pcs', 'Pieces')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
