# Generated by Django 5.2.9 on 2026-01-21 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0027_remove_order_order_type_remove_orderitem_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_chef',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='TFF.employees'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('branch_manager', 'Branch Manager'), ('staff', 'Staff'), ('chef', 'Chef')], max_length=20),
        ),
    ]
