# Generated by Django 5.2.9 on 2026-01-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0028_order_assigned_chef_alter_employees_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(db_index=True, default=1, editable=False, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
