# Generated by Django 5.2.9 on 2026-01-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0029_order_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='work_exprence',
            field=models.IntegerField(default=0, max_length=40),
        ),
    ]
