# Generated by Django 5.2.9 on 2026-01-26 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0030_employees_work_exprence'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderIngredientUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TFF.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_usages', to='TFF.order')),
            ],
            options={
                'unique_together': {('order', 'item')},
            },
        ),
    ]
