# Generated by Django 5.2.9 on 2026-01-27 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0031_orderingredientusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='assigned_chef',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'chef'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='TFF.employees'),
        ),
    ]
