# Generated by Django 5.2.9 on 2026-01-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0032_alter_order_assigned_chef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='sales',
            field=models.FloatField(),
        ),
    ]
