# Generated by Django 5.2.9 on 2026-01-27 12:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0033_alter_branch_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
