# Generated by Django 5.2.9 on 2026-01-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0034_alter_branch_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='work_exprence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('upto', 'Upto Percentage'), ('flat', 'Flat Amount')], max_length=20),
        ),
    ]
