# Generated by Django 5.2.9 on 2026-01-31 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0035_alter_employees_work_exprence_alter_offer_offer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiexCollect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TFF.branch')),
            ],
        ),
    ]
