# Generated by Django 5.2.9 on 2026-01-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0036_tiexcollect'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employees',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'branch_manager')), fields=('branch',), name='unique_branch_manager_per_branch'),
        ),
    ]
