# Generated by Django 5.2.9 on 2026-02-01 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFF', '0037_employees_unique_branch_manager_per_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TFF.branch'),
        ),
    ]
